Repository mobileappdevhm20/team-project-team_4, pull requests merged in 2020-06, with the labels that each got.

#52 Feature/#10 implement reminder
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/edu/hm/cs/ma/todoguru/MainActivity.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/database/LocalDateTimeConverter.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/database/Task.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/database/TaskDatabase.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/notification/ReminderNotification.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/BindingUtils.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/InsertTaskDialog.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/TaskViewModel.kt
  app/src/main/res/drawable/ic_notification_important_24px.xml
  app/src/main/res/layout/insert_task_dialog.xml
  app/src/main/res/values/strings.xml
Labels: Sprint 1

#59 Feature/#57 update gradle 4.0.0
  app/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: Sprint 1

#60 Feature/#58 Update dependencies
  app/build.gradle
Labels: Sprint 1

#56 #41 choose color scheme
  app/src/main/res/drawable/ic_done_all_24px.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/insert_task_dialog.xml
  app/src/main/res/layout/task_view_holder.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: Sprint 1

#62 [Spike] GitHub actions as CI
  .github/workflows/build.yml
  .travis.yml
  app/build.gradle
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/TaskDatabaseTest.kt
  build.gradle
Labels: Spike, Tech-Story

#63 Feature/#61 add readme with badges and license
  LICENSE
  README.md
Labels: Sprint 1

#67 Feature/#66 Due date after reminder
  app/build.gradle
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/MainActivityTest.kt
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/TaskDatabaseTest.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/MainActivity.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/database/TaskDatabase.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/notification/ReminderNotification.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/AbstractTaskDialog.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/InsertTaskDialog.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/TaskViewModel.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/UpdateTaskDialog.kt
  app/src/test/java/edu/hm/cs/ma/todoguru/task/ExampleUnitTest.kt
Labels: Sprint 2, bug

#68 Refactoring: Introducing fragments in order to simplify
  app/build.gradle
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/InsertTaskDialogScreenTestCase.kt
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/MainScreenTestCase.kt
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/SmokeTest.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/MainActivity.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/database/Task.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/DeleteDialog.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/TaskViewModel.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/TaskViewModelFactory.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/dialog/AbstractTaskDialog.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/dialog/DeleteDialog.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/dialog/InsertTaskDialog.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/dialog/UpdateTaskDialog.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/list/TaskAdapter.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/list/TaskListFragment.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/list/TaskWrapper.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/task_list_fragment.xml
  app/src/main/res/layout/task_view_holder.xml
  app/src/main/res/navigation/navigation.xml
  build.gradle
Labels: Sprint 2, Tech-Story

#73 Feature/#70 Bug -> app crashes on orientation change
  app/src/main/AndroidManifest.xml
Labels: Sprint 2, bug

#53 Feature/#8 display task
  app/build.gradle
  app/src/main/java/edu/hm/cs/ma/todoguru/ViewTaskFragment.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/database/TaskDatabaseDao.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/TaskViewModel.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/list/TaskAdapter.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/list/TaskListFragment.kt
  app/src/main/res/layout/task_view_holder.xml
  app/src/main/res/layout/view_task_fragment.xml
  app/src/main/res/navigation/navigation.xml
  app/src/main/res/values/ids.xml
  app/src/main/res/values/strings.xml
Labels: Sprint 2

#76 Changed the description of entering estimated time
  app/src/main/res/values/strings.xml
Labels: Sprint 2

#80 Feature/#18 Set an alarm
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/InsertTaskDialogScreenTestCase.kt
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/MainScreenTestCase.kt
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/TaskDatabaseTest.kt
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/Util.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/edu/hm/cs/ma/todoguru/task/ViewTaskFragment.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/dialog/SetAlarmDialog.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/list/TaskAdapter.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/list/TaskListFragment.kt
  app/src/main/res/drawable/ic_add_white_24dp.xml
  app/src/main/res/drawable/ic_alarm_add_24px.xml
  app/src/main/res/drawable/ic_keyboard_arrow_right_24px.xml
  app/src/main/res/drawable/ic_more_vert_24px.xml
  app/src/main/res/drawable/ic_notification_important_24px.xml
  app/src/main/res/drawable/ic_preview_24px.xml
  app/src/main/res/layout/task_view_holder.xml
  app/src/main/res/menu/item_menu.xml
  app/src/main/res/navigation/navigation.xml
  app/src/main/res/values/strings.xml
Labels: Sprint 2

#79 Feature/#74: Change insert and update task dialogs
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/InsertTaskDialogScreenTestCase.kt
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/InsertTaskFragmentScreenTestCase.kt
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/MainScreenTestCase.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/BindingUtils.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/BindingUtils.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/SetAlarmDialog.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/SetReminderFragment.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/TaskFragment.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/TaskViewModel.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/delete/DeleteDialog.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/dialog/AbstractTaskDialog.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/dialog/InsertTaskDialog.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/dialog/UpdateTaskDialog.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/insert/InsertTaskFragment.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/list/TaskAdapter.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/list/TaskListFragment.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/list/TaskListViewModel.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/read/ViewTaskFragment.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/update/UpdateTaskFragment.kt
  app/src/main/res/drawable/ic_alarm_24px.xml
  app/src/main/res/drawable/ic_topic_24px.xml
  app/src/main/res/layout/insert_task_fragment.xml
  app/src/main/res/layout/set_reminder_fragment.xml
  app/src/main/res/layout/task_list_fragment.xml
  app/src/main/res/layout/task_view_holder.xml
  app/src/main/res/layout/update_task_fragment.xml
  app/src/main/res/layout/view_task_fragment.xml
  app/src/main/res/navigation/navigation.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Sprint 2

#75 #22 explanation of app pages
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/ExplanationTest.kt
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/InsertTaskDialogScreenTestCase.kt
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/MainScreenTest.kt
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/MainScreenTestCase.kt
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/TaskDatabaseTest.kt
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/Util.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/explanation/ExplanationFragment.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/explanation/ExplanationFragmentThree.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/explanation/ExplanationFragmentTwo.kt
  app/src/main/res/drawable/ic_add_white_24dp.xml
  app/src/main/res/layout/explanation_pages.xml
  app/src/main/res/layout/explanation_pages_2.xml
  app/src/main/res/layout/explanation_pages_3.xml
  app/src/main/res/navigation/navigation.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: Sprint 2

#82 Feature/#13 task with categories
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/ExplanationTest.kt
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/InsertTaskDialogScreenTestCase.kt
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/MainScreenTestCase.kt
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/ToDoGuruDatabaseTest.kt
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/Util.kt
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/categories/InsertCategoryActionTest.kt
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/categories/InsertCategoryCancelButtonTest.kt
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/categories/InsertCategoryConfirmButtonTest.kt
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/categories/InsertCategoryFragmentScreenTest.kt
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/categories/Util.kt
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/explanation/ExplanationNextButtonTest.kt
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/explanation/ExplanationOneSkipButtonTest.kt
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/explanation/ExplanationPreviousButtonTest.kt
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/explanation/ExplanationThreeSkipButtonTest.kt
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/explanation/ExplanationTwoSkipButtonTest.kt
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/explanation/Util.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/BindingUtils.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/database/Category.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/database/CategoryDatabaseDao.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/database/Task.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/database/ToDoGuruDatabase.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/explanation/ExplanationFragment.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/explanation/ExplanationFragmentThree.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/explanation/ExplanationFragmentTwo.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/notification/ReminderNotification.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/SetAlarmDialog.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/SetCategoryDialog.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/SetReminderFragment.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/TaskFragment.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/TaskViewModel.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/categories/CategoryAdapter.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/categories/CategoryListFragment.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/categories/CategoryListViewModel.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/delete/DeleteCategoryDialog.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/delete/DeleteTaskDialog.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/insert/InsertCategoryDialog.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/insert/InsertTaskFragment.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/list/TaskListFragment.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/update/UpdateTaskFragment.kt
  app/src/main/res/drawable/ic_category_24px.xml
  app/src/main/res/drawable/ic_delete_24dp.xml
  app/src/main/res/drawable/ic_menu_24px.xml
  app/src/main/res/layout/category_list_fragment.xml
  app/src/main/res/layout/category_view_holder.xml
  app/src/main/res/layout/explanation_pages.xml
  app/src/main/res/layout/explanation_pages_2.xml
  app/src/main/res/layout/explanation_pages_3.xml
  app/src/main/res/layout/insert_category_dialog.xml
  app/src/main/res/layout/insert_task_fragment.xml
  app/src/main/res/layout/update_task_fragment.xml
  app/src/main/res/navigation/navigation.xml
  app/src/main/res/values/strings.xml
Labels: Sprint 2

#85 Feature/#15 task on repeat
  app/build.gradle
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/SimpleUpdateTaskActionTest.kt
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/ToDoGuruDatabaseTest.kt
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/categories/InsertCategoryConfirmButtonTest.kt
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/repeat/InsertRepeatDialogActionTest.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/BindingUtils.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/database/PeriodConverter.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/database/Task.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/database/ToDoGuruDatabase.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/SetRepeatDialog.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/TaskFragment.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/TaskViewModel.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/insert/InsertTaskFragment.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/update/UpdateTaskFragment.kt
  app/src/main/res/drawable/ic_repeat_24px.xml
  app/src/main/res/layout/insert_task_fragment.xml
  app/src/main/res/layout/update_task_fragment.xml
  app/src/main/res/navigation/navigation.xml
Labels: Sprint 2

#86 time tracker
  app/src/main/java/edu/hm/cs/ma/todoguru/database/Time.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/database/TimeTrackerDatabaseDao.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/database/ToDoGuruDatabase.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/Util.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/read/ViewTaskFragment.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/timeTracker/TimeTrackerViewModel.kt
  app/src/main/res/layout/view_task_fragment.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: Sprint 2

#90 productivity view model and fragment created
  app/build.gradle
  app/src/main/java/edu/hm/cs/ma/todoguru/database/TaskDatabaseDao.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/productivity/ProductivityFragment.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/productivity/ProductivityViewModel.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/TaskFragment.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/list/TaskListFragment.kt
  app/src/main/res/drawable/ic_pie_chart_24dp.xml
  app/src/main/res/layout/productivity_fragment.xml
  app/src/main/res/layout/task_list_fragment.xml
  app/src/main/res/navigation/navigation.xml
  build.gradle
Labels: Sprint 2

#88 Feature/#77 design for view task fragment
  app/src/main/java/edu/hm/cs/ma/todoguru/task/read/ViewTaskFragment.kt
  app/src/main/res/drawable/calendar_today_24.xml
  app/src/main/res/drawable/category_24.xml
  app/src/main/res/drawable/ic_baseline_notification_important_24.xml
  app/src/main/res/drawable/message_24.xml
  app/src/main/res/drawable/subject_24.xml
  app/src/main/res/layout/task_view_holder.xml
  app/src/main/res/layout/view_task_fragment.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: Sprint 2

#95 Feature/#28 contact developer team
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/AndroidTestSuite.kt
  app/src/androidTest/java/edu/hm/cs/ma/todoguru/ContactDevelopersTest.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/list/TaskListFragment.kt
  app/src/main/res/menu/menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Sprint 3

#93 Release v3.0
  docs/retrospective_sprint_2.pdf
Labels: Sprint 3

#97 Feature/#29 privacy policy
  app/src/main/assets/privacy_policy.html
  app/src/main/java/edu/hm/cs/ma/todoguru/privacy/PrivacyPolicyFragment.kt
  app/src/main/java/edu/hm/cs/ma/todoguru/task/list/TaskListFragment.kt
  app/src/main/res/layout/privacy_policy_fragment.xml
  app/src/main/res/menu/menu.xml
  app/src/main/res/navigation/navigation.xml
  app/src/main/res/values/strings.xml
Labels: Sprint 3

#92 Feature/#91 google analytics crashlytics
  app/build.gradle
  app/google-services.json
  app/src/main/AndroidManifest.xml
  build.gradle
Labels: Sprint 2
